---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.database.appName }}
spec:
  replicas: {{ .Values.database.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.database.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.database.appName }}
    spec:
      containers:
        - name: {{ .Values.database.appName }}
          image: "{{ .Values.database.registry }}/{{ .Values.database.project }}/{{ .Values.database.image }}:{{ .Values.database.tag }}"
          env:
            - name: POSTGRES_USER
              value: {{ .Values.database.env.POSTGRES_USER }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.database.env.POSTGRES_PASSWORD }}
          ports:
            - containerPort: {{ .Values.database.port }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-storage
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: database-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.persistence.size }}
  storageClassName: {{ .Values.database.persistence.storageClass }}
