---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.database.appName }}
spec:
  replicas: {{ .Values.database.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.database.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.database.appName }}
    spec:
      containers:
        - name: {{ .Values.database.appName }}
          image: "{{ .Values.database.registry }}/{{ .Values.database.image }}:{{ .Values.database.tag }}"
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: MONGO_INITDB_ROOT_PASSWORD
          ports:
            - containerPort: {{ .Values.database.port }}
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-data
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: database-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.appName }}
spec:
  selector:
    app: {{ .Values.database.appName }}
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.database.port }}
      targetPort: {{ .Values.database.targetPort }}
  type: {{ .Values.service.type }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.database.appName }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.persistence.size }}
