apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.appName }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.appName }}
    spec:
      containers:
        - name: {{ .Values.frontend.appName }}
          image: "{{ .Values.frontend.registry }}/{{ .Values.frontend.project }}/{{ .Values.frontend.image }}:{{ .Values.frontend.tag }}"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.appName }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.targetPort }}
  selector:
    app: {{ .Values.frontend.appName }}