apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: login-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.frontendPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.frontend.appName }}
                port:
                  number: {{ .Values.frontend.port }}
          - path: {{ .Values.ingress.backendPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.backend.appName }}
                port:
                  number: {{ .Values.backend.port }}
