apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: login-app
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements
      - namespace: dev
      - namespace: qa
      - namespace: prod
  template:
    metadata:
      name: 'login-app-{{.namespace}}'
    spec:
      destination:
        namespace: '{{.namespace}}'
        server: https://kubernetes.default.svc
      project: default
      source:
        repoURL: https://github.com/pauljosepq/deploy-sample
        targetRevision: main
        path: helm
        helm:
          releaseName: login-app
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true