replicaCount: 1
commonRegistry: &commonRegistry docker.io
commonProject: &commonProject do-community

backend:
  appName: backend
  service:
    type: ClusterIP
    port: 3000
  registry: *commonRegistry
  project: *commonProject
  image: backend-image
  tag: latest
  port: 3000

frontend:
  appName: frontend
  service:
    type: ClusterIP
    port: 80
  registry: *commonRegistry
  project: *commonProject
  image: frontend-image
  tag: latest
  port: 80

database:
  registry: *commonRegistry
  project: *commonProject
  image: postgres
  tag: latest
  port: 5432
  env:
    POSTGRES_USER: "admin"
    POSTGRES_PASSWORD: "admin"
  persistence:
    enabled: true
    storageClass: standard
    size: 1Gi

ingress:
  enabled: true
  host: login-app.local
  backendPath: /api
  frontendPath: /

service:
  type: ClusterIP
