commonRegistry: &commonRegistry ghcr.io
commonProject: &commonProject pauljosepq

backend:
  replicaCount: 1
  appName: backend
  service:
    type: ClusterIP
    port: 3000
  registry: *commonRegistry
  project: *commonProject
  image: login-app-backend
  tag: "1.1.9"
  port: 3000
  targetPort: 3000
  env:
    PORT: "3000"
    MONGODB_URI: "mongodb://admin:admin@database:27017"

frontend:
  replicaCount: 1
  appName: frontend
  service:
    type: ClusterIP
    port: 80
  registry: *commonRegistry
  project: *commonProject
  image: login-app-frontend
  tag: "1.1.9"
  port: 80
  targetPort: 4000

database:
  replicaCount: 1
  appName: database
  registry: docker.io
  project: ""
  image: mongo
  tag: "8.0.5-rc2-noble"
  port: 27017
  targetPort: 27017
  env:
    MONGO_INITDB_ROOT_USERNAME: "admin"
    MONGO_INITDB_ROOT_PASSWORD: "admin"
  persistence:
    size: 1Gi

ingress:
  enabled: true
  host: login-app.dev.example.com
  frontend:
    path: /
    pathType: Prefix
  backend:
    path: /api(/|$)(.*)
    pathType: ImplementationSpecific

service:
  protocol: TCP
  type: ClusterIP
