commonRegistry: &commonRegistry ghcr.io
commonProject: &commonProject pauljosepq

backend:
  appName: backend
  service:
    type: ClusterIP
    port: 3000
  registry: *commonRegistry
  project: *commonProject
  image: login-app-backend
  tag: "1.0.0"
  port: 3000

frontend:
  appName: frontend
  service:
    type: ClusterIP
    port: 80
  registry: *commonRegistry
  project: *commonProject
  image: login-app-frontend
  tag: "1.0.0"
  port: 80

database:
  replicaCount: 1
  appName: database
  registry: *commonRegistry
  project: *commonProject
  image: login-app-database
  tag: "1.0.0"
  port: 5432
  env:
    POSTGRES_USER: "admin"
    POSTGRES_PASSWORD: "admin"
  persistence:
    enabled: true
    storageClass: standard
    size: 1Gi

ingress:
  enabled: true
  backendPath: /api
  frontendPath: /

service:
  type: ClusterIP
